version: 2

run:
  timeout: 5m
  tests: false
  skip-dirs:
    - vendor
    - .git
    - .history
  skip-files:
    - ".*_test.go$"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude errors in test files
    - path: _test\.go
      linters:
        - errcheck

    # Exclude errors in generated files
    - path: wire_gen\.go
      linters:
        - errcheck
        - staticcheck

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
