package commands

import (
	"fmt"
	"os/exec"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/lisvindanuu/anaphase-cli/internal/generator"
	"github.com/lisvindanuu/anaphase-cli/internal/ui"
	"github.com/spf13/cobra"
)

var genSwaggerCmd = &cobra.Command{
	Use:   "swagger",
	Short: "Generate Swagger/OpenAPI documentation",
	Long: `Generate Swagger/OpenAPI documentation for your API.

This command will:
- Add Swagger annotations to handlers
- Generate swagger.json and swagger.yaml
- Add /swagger endpoint to your API

Example:
  anaphase gen swagger --domain customer
  anaphase gen swagger --domain product --title "Product API" --version "2.0"`,
	RunE: runGenSwagger,
}

var (
	swaggerDomain      string
	swaggerTitle       string
	swaggerDescription string
	swaggerVersion     string
	swaggerHost        string
	swaggerBasePath    string
)

func init() {
	genSwaggerCmd.Flags().StringVar(&swaggerDomain, "domain", "", "Domain to generate Swagger docs for (leave empty for all)")
	genSwaggerCmd.Flags().StringVar(&swaggerTitle, "title", "Anaphase API", "API title")
	genSwaggerCmd.Flags().StringVar(&swaggerDescription, "description", "API generated by Anaphase CLI", "API description")
	genSwaggerCmd.Flags().StringVar(&swaggerVersion, "version", "1.0", "API version")
	genSwaggerCmd.Flags().StringVar(&swaggerHost, "host", "localhost:8080", "API host")
	genSwaggerCmd.Flags().StringVar(&swaggerBasePath, "base-path", "/api/v1", "API base path")

	genCmd.AddCommand(genSwaggerCmd)
}

func runGenSwagger(cmd *cobra.Command, args []string) error {
	// Create steps for progress
	steps := []string{
		"Scanning domains",
		"Adding Swagger annotations",
		"Generating Swagger documentation",
		"Creating /swagger endpoint",
	}

	progress := ui.NewMultiStepProgress(steps)

	// Create Bubble Tea program
	model := &swaggerGeneratorModel{
		domain:      swaggerDomain,
		title:       swaggerTitle,
		description: swaggerDescription,
		version:     swaggerVersion,
		host:        swaggerHost,
		basePath:    swaggerBasePath,
		progress:    progress,
	}

	p := tea.NewProgram(model)
	finalModel, err := p.Run()
	if err != nil {
		return fmt.Errorf("failed to run UI: %w", err)
	}

	// Check for errors
	if m, ok := finalModel.(*swaggerGeneratorModel); ok {
		if m.err != nil {
			return m.err
		}

		// Print success summary
		fmt.Println()
		fmt.Println(ui.RenderSuccess("Swagger documentation generated!"))
		fmt.Println()
		fmt.Println(ui.RenderInfo("Swagger UI available at: http://" + swaggerHost + "/swagger/"))
		fmt.Println(ui.RenderInfo("Swagger JSON: http://" + swaggerHost + "/swagger/doc.json"))
		fmt.Println()
		fmt.Println(ui.RenderSubtle("To regenerate docs after changes, run:"))
		fmt.Println(ui.RenderSubtle("  swag init -g cmd/api/main.go"))
	}

	return nil
}

// swaggerGeneratorModel is the Bubble Tea model for Swagger generation
type swaggerGeneratorModel struct {
	domain      string
	title       string
	description string
	version     string
	host        string
	basePath    string
	progress    *ui.MultiStepProgress
	done        bool
	err         error
}

// Init initializes the model
func (m *swaggerGeneratorModel) Init() tea.Cmd {
	return m.runGeneration()
}

// swaggerDoneMsg indicates generation completion
type swaggerDoneMsg struct {
	err error
}

// runGeneration executes the Swagger generation
func (m *swaggerGeneratorModel) runGeneration() tea.Cmd {
	return func() tea.Msg {
		// Step 1: Generate annotations
		config := &generator.SwaggerConfig{
			Domain:      m.domain,
			Title:       m.title,
			Description: m.description,
			Version:     m.version,
			Host:        m.host,
			BasePath:    m.basePath,
		}

		gen := generator.NewSwaggerGenerator(config)
		if err := gen.Generate(); err != nil {
			return swaggerDoneMsg{err: err}
		}

		// Step 2: Run swag init
		cmd := exec.Command("swag", "init", "-g", "cmd/api/main.go", "-o", "docs")
		if err := cmd.Run(); err != nil {
			return swaggerDoneMsg{err: fmt.Errorf("swag init failed: %w (make sure swag is installed: go install github.com/swaggo/swag/cmd/swag@latest)", err)}
		}

		return swaggerDoneMsg{err: nil}
	}
}

// Update updates the model
func (m *swaggerGeneratorModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		if msg.String() == "ctrl+c" {
			return m, tea.Quit
		}

	case swaggerDoneMsg:
		m.done = true
		m.err = msg.err
		if m.err == nil {
			m.progress.SetCurrent(m.progress.Total)
		}
		return m, tea.Quit
	}

	return m, nil
}

// View renders the model
func (m *swaggerGeneratorModel) View() string {
	if m.done {
		if m.err != nil {
			return ui.RenderError(fmt.Sprintf("Swagger generation failed: %v", m.err))
		}
		return ""
	}

	header := ui.RenderTitle("Generating Swagger Documentation")
	return fmt.Sprintf("%s\n\n%s\n", header, m.progress.View())
}
